---
title: "Old Faithful Eruptions"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    social: menu
    source_code: embed
runtime: shiny
---

```{r global, include=FALSE}
# load data in 'global' chunk so it can be shared by all users of the dashboard
library(datasets)
data(faithful)
```

Column {.sidebar}
-----------------------------------------------------------------------

Waiting time between eruptions and the duration of the eruption for the
Old Faithful geyser in Yellowstone National Park, Wyoming, USA.

```{r}
  
  selectInput(inputId = "n_grietas",
              label = "Number of bins in histograma (approximate):",
              choices = c(10, 20, 35, 50),
              selected = 20)
  sliderInput("bw_adjust", label = "Bandwidth adjustment:",
            min = 0.2, max = 2, value = 1, step = 0.2)
  sliderInput(inputId = "constante_vertical",
              label = "Vertical constant",
              min = min(faithful$eruptions), max = max(faithful$eruptions),value =                       mean(faithful$eruptions), step = 0.5)
  
```

Column
-----------------------------------------------------------------------

### Geyser Eruption Duration

```{r}
renderPlot({
  hist(faithful$eruptions, probability = TRUE, breaks = as.numeric(input$n_grietas),
       xlab = "Duration (minutes)", main = "Geyser Eruption Duration", col = "gray")
  
  abline(v = input$constante_vertical, col = "red")
  
  dens <- density(faithful$eruptions, adjust = input$bw_adjust)
  lines(dens, col = "blue")
})
```
`